package co.istad.fary.elearning.features.course;

import co.istad.fary.elearning.features.category.Category;
import co.istad.fary.elearning.features.category.CategoryRepository;
import co.istad.fary.elearning.features.course.dto.CourseResponse;
import co.istad.fary.elearning.features.course.dto.CreateCourseRequest;
import co.istad.fary.elearning.features.instructor.InstructorProfile;
import co.istad.fary.elearning.security.AuthUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;

@Service
@Slf4j
@RequiredArgsConstructor
public class CourseServiceImpl implements CourseService{

    private final CourseRepository courseRepository;
    private final CategoryRepository categoryRepository;
    private final CourseMapper courseMapper;

    @Override
    public CourseResponse createCourse(CreateCourseRequest createCourseRequest) {
        // TODO: write your logic
        // Validate slug
        if (courseRepository.existsBySlug(createCourseRequest.slug())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Slug has already been used");
        }

        // Validate category
        Category category = categoryRepository.findById(createCourseRequest.categoryId())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Category has not been found"));

        // Transfer data from DTO to Domain Model
        Course course = courseMapper
                .mapCreateCourseRequestToCourse(createCourseRequest);

        // System data (generated by system)
        course.setCategory(category);
        course.setCountRating(0);
        course.setStarRating(0F);
        course.setIsDeleted(false);
        course.setIsPublished(false);
        course.setUpdatedAt(LocalDateTime.now());
        course.setInstructorProfile(new InstructorProfile(AuthUtils.extractUserId()));

        course = courseRepository.save(course);

        return courseMapper.mapCourseToCourseResponse(course);
    }

}